import { RoadmapData } from "@/lib/types";
import { useState } from "react";
import RoadmapStep from "./RoadmapStep";
import Button from "../ui/Button";
import ProgressBar from "./ProgressBar";
import RoadmapError from "./RoadmapError";

interface RoadmapDisplayProps {
  content: string;
  onCreateNew: () => void;
}

export default function RoadmapDisplay({
  content,
  onCreateNew,
}: RoadmapDisplayProps) {
  const [completedSteps, setCompletedSteps] = useState<Set<number>>(new Set());

  let roadmapData: RoadmapData;
  try {
    const parsedContent = JSON.parse(content);

    if (parsedContent.error) {
      return (
        <RoadmapError error={parsedContent.error} onCreateNew={onCreateNew} />
      );
    }

    if (!parsedContent.steps || !Array.isArray(parsedContent.steps)) {
      return (
        <RoadmapError
          title="Invalid Roadmap Data"
          error="The response does not contain valid roadmap steps. Please try generating a new roadmap."
          onCreateNew={onCreateNew}
          showTroubleshooting={false}
        />
      );
    }

    roadmapData = parsedContent;
  } catch (error) {
    console.error("Failed to parse roadmap content:", error);
    return (
      <RoadmapError
        title="Invalid Roadmap Data"
        error="The roadmap content could not be parsed. Please try generating a new roadmap."
        onCreateNew={onCreateNew}
        showTroubleshooting={false}
      />
    );
  }

  const toggleStepCompletion = (stepIndex: number) => {
    setCompletedSteps((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(stepIndex)) {
        newSet.delete(stepIndex);
      } else {
        newSet.add(stepIndex);
      }
      return newSet;
    });
  };

  const progressPercentage =
    (completedSteps.size / roadmapData.steps.length) * 100;

  return (
    <div className="mx-auto max-w-4xl rounded-2xl bg-white p-8 shadow-xl">
      <div className="mb-6 flex items-start justify-between">
        <div>
          <h2 className="mb-2 text-2xl font-bold text-gray-900">
            Your Learning Roadmap
          </h2>
          <p className="text-gray-600">
            Here&apos;s your personalized learning path generated by AI
          </p>
          <div className="mt-2 flex items-center gap-4">
            <span className="text-sm text-gray-500">
              Total Duration: <strong>{roadmapData.totalTimeframe}</strong>
            </span>
            <span className="text-sm text-gray-500">
              Progress:{" "}
              <strong>
                {completedSteps.size}/{roadmapData.steps.length} steps
              </strong>
            </span>
            <div className="flex gap-2">
              {roadmapData.tags.map((tag, index) => (
                <span
                  key={index}
                  className="rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-800"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>

          <ProgressBar progressPercentage={progressPercentage} />
        </div>
        <Button onClick={onCreateNew}>Create New Roadmap</Button>
      </div>

      <div className="border-t border-gray-200 pt-6">
        <div className="space-y-6">
          {roadmapData.steps.map((step, index) => (
            <RoadmapStep
              key={index}
              index={index}
              completedSteps={completedSteps}
              step={step}
              toggleStepCompletion={toggleStepCompletion}
              isPreview={true}
            />
          ))}
        </div>
      </div>

      {/* <div className="mt-8 rounded-lg bg-amber-50 p-4">
        <p className="text-sm text-amber-800">
          <strong>Tip:</strong> Click on the step numbers to mark them as
          completed and track your progress.
          {progressPercentage === 100 && (
            <span className="mt-1 block font-semibold text-green-800">
              🎉 Congratulations! You&apos;ve completed your learning roadmap!
            </span>
          )}
        </p>
      </div> */}
    </div>
  );
}
