packages:
  - name: ai
    actions:
      - name: generateRoadmap
        runtime: "python:3.11"
        limits:
          timeout: 20000
          memory: 256
  - name: users
    actions:
      - name: saveUser
        runtime: "python:3.11"
        limits:
          timeout: 5000
          memory: 256
      - name: getUser
        runtime: "python:3.11"
        limits:
          timeout: 5000
          memory: 256
environment:
  AGENT_ENDPOINT: ${AGENT_ENDPOINT}
  AGENT_ACCESS_KEY: ${AGENT_ACCESS_KEY}
  DATABASE_URL: ${DATABASE_URL}
